### ISSUE TITLE
0.28.0 shows no files

### ISSUE THREAD

**Issue by savchenko** [gitui-org/gitui#2820]
**Describe the bug**
v0.28.0 fails to show any modified files.

**To Reproduce**
1. Update to 0.28.0 from 0.26.3
2. Go to a local repo which is symlinked from elsewhere
3. Observe empty status

**Expected behavior**
Modified/delete/new files are visible.

**Screenshots**

### v0.26.3
<img width="527" height="337" alt="Image" src="https://github.com/user-attachments/assets/6e98a902-8b45-4e1a-9e83-e896f66fa7a7" />

### v0.28.0
<img width="528" height="412" alt="Image" src="https://github.com/user-attachments/assets/c6afb9f5-7b79-4542-96d5-457ff66f49f0" />

**Context (please complete the following information):**
 - OS/Distro + Version: Debian 13.2
 - GitUI Version 0.28.0
 - Rust version: N/A, downloaded the release binary from GitHub

**Additional context**
I have double-checked that the content is actually not there and not just rendered in the BG colour:

<img width="605" height="690" alt="Image" src="https://github.com/user-attachments/assets/d4c93f6b-cd73-45db-ac86-4b6f87662a66" />

**Comment by extrawurst** [comment]
@savchenko do you have a reproducer for us?

@cruessler I am afraid this might be due to our switch to gitoxide?

**Comment by cruessler** [comment]
@extrawurst Yes, it sounds very likely that this is due to the switch to `gitoxide` in the status tab.

@savchenko Can you elaborate as to what you mean by “Go to a local repo which is symlinked from elsewhere”?

**Comment by savchenko** [comment]
In this particular case:

```bash
$ pwd
/home/user/.config/nvim
$ pwd | xargs realpath
/home/user/.dotfiles/config/nvim
```

0.26.3 and 0.28.0 running from the same `$PWD` side-to-side, 0.28.0 shows current path in the title:

<img width="981" height="213" alt="Image" src="https://github.com/user-attachments/assets/c7424dc5-96f7-4d2b-a5f6-a521e2345601" />

**Comment by extrawurst** [comment]
@savchenko if you want to help us, please share a shell script that sets-up a repo that reproduces the problem

**Comment by savchenko** [comment]
Surprisingly, I can't. This was supposed to do it:

```bash
#!/bin/env bash

echo -e "\nhttps://github.com/gitui-org/gitui/issues/2820\n"

TIMESTAMP=$(date +%H-%M)

mkdir -p "$HOME/.test_${TIMESTAMP}/some/path"
TF=$(realpath "$HOME/.test_${TIMESTAMP}/some/path")
cd $TF && cd ../.. || exit 1

git init && git config --local commit.gpgsign false
git -C "$TF" config user.email "test@example.com"
git -C "$TF" config user.name "Test User"

touch "$TF/foo" "$TF/bar" "$TF/blah"
echo "merry" > "$TF/foo"
echo "christmas" > "$TF/bar"
git -C "$TF" add foo bar &> /dev/null
git -C "$TF" commit -m "Initial commit" &> /dev/null
echo "new year" > "$TF/bar"

RPATH="$HOME/.config/repro_${TIMESTAMP}"
ln -s "$TF/" "$RPATH"

echo "cd to '$RPATH' and run 'gitui'"
```

...but it doesn't result in a reproducible structure. What I have noticed, however, is that the bug can be reliably fixed with `realpath . | xargs gitui0280 --directory`.

**Comment by cruessler** [comment]
Unfortunately, I still don’t understand your setup, so I’m mostly confused at this point. Do you have a `.git` folder in your `$HOME` folder? What is the output of `git status` run in the same directory that you run `gitui` 0.28 in? Do you have symbolic links in your repository to locations outside of it?

**Comment by savchenko** [comment]
@cruessler,

> Unfortunately, I still don’t understand your setup, so I’m mostly confused at this point.

- `~/.dotfiles/` is the git repository.
- `~/.config/nvim/` is the symlink to the `~/.dotfiles/config/nvim`

> What is the output of git status run in the same directory that you run gitui 0.28 in?

- The bug occurs with either clean or dirty repository.

> Do you have symbolic links in your repository to locations outside of it?

- No, the symlinks are pointing _to_ the folders in the repository.

The fact that starting `gitui` with `--directory` pointing to the `realpath` works, makes me think that the issue might be with the path resolution.

**Comment by cruessler** [comment]
I have a setup similar to yours. I keep my dotfiles in `~/repos/dotfiles` and symlink to them from `~`. I have not been able to reproduce your issue, though. Whether I run `gitui` inside `~/repos/dotfiles` or inside `~/repos/dotfiles/.config/nvim`, I can see all the files that have changes.

My `~/.config` is a directory, my `~/.config/nvim` is a symlink to `~/repos/dotfiles/.config/nvim`. Even when I run `gitui` inside `~/repos/dotfiles/.config/nvim`, I get the same results as when I run it inside `~/repos/dotfiles`.

Which directory do you run `realpath .` in? My suspicion is that you don’t run `gitui` inside your `~/.dotfiles`, but elsewhere, though I can’t really tell based on your comments.

You could also run `gitui --logfile <...>`, maybe there’s something helpful there.

**Comment by savchenko** [comment]
> Which directory do you run realpath . in?

As mentioned [above](https://github.com/gitui-org/gitui/issues/2820#issuecomment-3691868471), `/home/user/.dotfiles/config/nvim`.

Indeed, I forgot about logging and checked only the non-existing `--verbose`! Here it is:
```
13:07:50 [TRACE] (1) gitui::app: [src/app.rs:164] open repo at: RefCell { value: Path(".") }
13:07:50 [TRACE] (6) mio::poll: [/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mio-1.0.3/src/poll.rs:571] registering event source with poller: token=Token(0), interests=READABLE
13:07:50 [TRACE] (6) mio::poll: [/home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/mio-1.0.3/src/poll.rs:571] registering event source with poller: token=Token(1), interests=READABLE
13:07:50 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:102] request: [hash: 883513528202634858] (type: WorkingDir)
13:07:50 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:102] request: [hash: 17898145822719004600] (type: Stage)
13:07:50 [TRACE] (1) gitui: [src/main.rs:268] app start: 21 ms
13:07:50 [TRACE] (1) gitui::app: [src/app.rs:404] update
13:07:50 [TRACE] (3) asyncgit::status: [asyncgit/src/status.rs:160] status fetched: 17898145822719004600 (type: Stage)
13:07:50 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:96] request blocked, still pending
13:07:50 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:102] request: [hash: 10569998816996189622] (type: Stage)
13:07:50 [ERROR] fetch_helper: gix error:gix::status::index_worktree::Error error: Could not determine status for submodule at 'local/share/fonts'
13:07:50 [TRACE] (3) asyncgit::status: [asyncgit/src/status.rs:160] status fetched: 10569998816996189622 (type: Stage)
13:07:50 [TRACE] (1) gitui::app: [src/app.rs:424] update_async: Git(Status)
13:07:50 [TRACE] (1) gitui::app: [src/app.rs:424] update_async: Git(Status)
13:07:50 [TRACE] (1) gitui::app: [src/app.rs:424] update_async: Git(Status)
13:07:51 [TRACE] (1) gitui::app: [src/app.rs:307] event: Input(Key(KeyEvent { code: Char('c'), modifiers: KeyModifiers(CONTROL), kind: Press, state: KeyEventState(0x0) }))
```

Submodule to blame? This `[ERROR]` is absent in the **0.26.3** log:

```
13:10:44 [TRACE] (1) gitui::app: [src/app.rs:154] open repo at: RefCell { value: Path(".") }
13:10:44 [TRACE] (6) mio::poll: [/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.11/src/poll.rs:551] registering event source with poller: token=Token(0), interests=READABLE
13:10:44 [TRACE] (6) mio::poll: [/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/mio-0.8.11/src/poll.rs:551] registering event source with poller: token=Token(1), interests=READABLE
13:10:44 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:102] request: [hash: 10466632455707412603] (type: WorkingDir)
13:10:44 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:102] request: [hash: 10538978654856541294] (type: Stage)
13:10:44 [TRACE] (1) gitui: [src/main.rs:215] app start: 34 ms
13:10:44 [TRACE] (1) gitui::app: [src/app.rs:375] update
13:10:44 [TRACE] (2) asyncgit::status: [asyncgit/src/status.rs:160] status fetched: 10538978654856541294 (type: Stage)
13:10:44 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:96] request blocked, still pending
13:10:44 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:102] request: [hash: 11915883565713119088] (type: Stage)
13:10:44 [TRACE] (2) asyncgit::status: [asyncgit/src/status.rs:160] status fetched: 11915883565713119088 (type: Stage)
13:10:44 [TRACE] (3) asyncgit::status: [asyncgit/src/status.rs:160] status fetched: 10466632455707412603 (type: WorkingDir)
13:10:44 [TRACE] (1) gitui::app: [src/app.rs:395] update_async: Git(Status)
13:10:44 [TRACE] (1) gitui::app: [src/app.rs:395] update_async: Git(Status)
13:10:44 [TRACE] (1) gitui::app: [src/app.rs:395] update_async: Git(Status)
13:10:46 [TRACE] (1) gitui::app: [src/app.rs:278] event: Input(Key(KeyEvent { code: Char('c'), modifiers: KeyModifiers(CONTROL), kind: Press, state: KeyEventState(0x0) }))
```

**Comment by cruessler** [comment]
That `ERROR` is highly likely to blame, thanks for the follow-up! I suspect this is the line causing the error in `gitui`: https://github.com/gitui-org/gitui/blob/463c411db53cf0914e88d3b9864b0c26bf9fe81f/asyncgit/src/sync/status.rs#L202

This is the error message in `gitoxide`: https://github.com/GitoxideLabs/gitoxide/blob/a000a7337d7e481ed2e576f66316cbcf0b01e19d/gix-status/src/index_as_worktree/types.rs#L18-L22. Unfortunately, `source` is not part of the error message, so we don’t really know what’s causing the error yet. You could try and compile `gitoxide` on your machine and then run `gix status` inside `~/.config/nvim`. Maybe we’re lucky and we get a better error message. If not, you could compile `gitoxide` from source, changing it to include `source` in the error message.

**Comment by savchenko** [comment]
OK, here is the comparison between `git` and `gix`.

#### git

```
> git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   ../bash/aliases.sh
	deleted:    after/syntax/wf.vim

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	after/syntax/wb.vim
```

#### gitoxide

```
> /home/user/Downloads/gitoxide-max-pure-v0.48.0-x86_64-unknown-linux-gnu/gix status
  M ../bash/aliases.sh
  ? after/syntax/
  D after/syntax/wf.vim
Error: Could not determine status for submodule at 'local/share/fonts'

Caused by:
    A working tree is required to perform a directory walk
```

I wonder if this is related to https://github.com/GitoxideLabs/gitoxide/issues/2052

**Comment by cruessler** [comment]
@Byron Would you mind having a brief look at this issue? Are you able to infer anything obvious from the above error message?

**Comment by cruessler** [comment]
@savchenko It might indeed be realted. Would you be able to create a script that sets up your repository including a submodule that can be used to reproduce the error, similar e. g. to this one: https://github.com/GitoxideLabs/gitoxide/blob/main/gix-dir/tests/fixtures/many.sh (or any other in `gitoxide`, for that matter)?

**Comment by savchenko** [comment]
@cruessler , the script below reproduces the issue reliably:

```bash
#!/bin/env bash

echo -e "\nhttps://github.com/gitui-org/gitui/issues/2820\n"

TS=$(date +%H-%M)
mkdir -p "$HOME/.test_${TS}/some/path"
TF=$(realpath "$HOME/.test_${TS}/some/path")
cd "$TF" && cd ../.. || exit 1

git init && git config --local commit.gpgsign false || exit 1
git -C "$TF" config user.email "test@example.com"
git -C "$TF" config user.name "Test User"

touch "$TF/foo" "$TF/bar" "$TF/blah"
echo "merry" > "$TF/foo"
echo "christmas" > "$TF/bar"
git -C "$TF" add foo bar &> /dev/null
git -C "$TF" commit -m "Initial commit" &> /dev/null
echo "new year" > "$TF/bar"

cd "$HOME/.test_${TS}" || exit 1
GIT_TERMINAL_PROMPT=0 git submodule add "https://github.com/savchenko/reproGitui2820" one/two &> /dev/null || exit 1
git commit -am "Added submodule to reproduce the gitoxide bug..."
git submodule update --init --recursive &> /dev/null || exit 1

RPATH="$HOME/.config/repro_${TS}"
ln -s "$TF/" "$RPATH"

echo -e "\ncd to '$RPATH' and run gitui v0.28.0"
```

**Comment by Byron** [comment]
Thanks for summoning me, this does look like a shortcoming in `gix status` that has to be addressed there.
Meanwhile, since `gix status` is able to print initial results, would it be possible to make `gitui` more robust against individual item failures by using the [status iterator](https://github.com/GitoxideLabs/gitoxide/blob/5da38e5a473979965b622869c4676f0f21bed58b/gitoxide-core/src/repository/status.rs#L73-L76)?

**Comment by cruessler** [comment]
@Byron Thanks for the suggestion! As far as I can tell, the issue turned out to be the seemingly innocuous `let item = item?;` that will abort the entire status iter in `gitui` and won’t report any of the items that didn’t produce an error.

@savchenko Thanks a lot for the repro that was very helpful! Would you be able to check whether the draft PR I opened with a workaround for your issue (#2821) fixes it?

**Comment by savchenko** [comment]
@cruessler , can confirm that building `--release` from 463c411db53cf0914e88d3b9864b0c26bf9fe81f with your patch applied works.

I can see the modified files and the following is logged if executed with `--logging`:
```
11:21:24 [WARN] [status] the status iter returned an error for an item: Err(IndexAsWorktreeWithRenames(TrackedFileModifications(SubmoduleStatus { rela_path: "local/share/fonts", source: SubmoduleStatus(NextStatusItem(IndexWorktree(MissingWorkDir))) })))
```

**Comment by kakalos12** [comment]
This error occurred in my project. I'm not sure if this is right but i have some folder / files which belongs to another users in my repo (like the docker database file that is set to some random uid). After adding the files to ignore, it's working fine. Not sure if it's related.

**Comment by Byron** [comment]
If `gitui` doesn't care about the shortest-possible path, this can be fixed by obtaining the canonicalised or realpath on the discovered repository. For that, there is `gix::discover::upwards(…)` to find a repository, and that path one can free of indirections. And if `gitui` never shows these paths anyway, i.e. shows repo-relative paths all the time, then this might be a good solution even.

Besides that, I am looking into it, as I could reproduce it in the example, but not yet in a test even though that should work as well.

**Comment by Byron** [comment]
Ok, the fix is here https://github.com/GitoxideLabs/gitoxide/pull/2312 and I plan to create a new release this year.

**Comment by savchenko** [comment]
> and I plan to create a new release this year

364.9 days to go :-)

**Comment by extrawurst** [comment]
> Ok, the fix is here [GitoxideLabs/gitoxide#2312](https://github.com/GitoxideLabs/gitoxide/pull/2312) and I plan to create a new release this year.

Wait you are still in 2025, right? So release today 🥳 happy new year

**Comment by Byron** [comment]
Yeah, and reading this makes me feel like I am stuck in the past :P. HNY!

**Comment by extrawurst** [comment]
Nonetheless I merged #2821 - thanks @cruessler I believe not crashing makes sense anyway and rather logging away. @savchenko the next nightly build should already contain the fix

**Comment by extrawurst** [comment]
So we also update gix now, I consider this fixed now
